using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibraryProjectUWP.Code.Helpers
{
    public class CountryHelpers
    {
        public static IEnumerable<string> LanguagesList()
        {
            try
            {
                List<string> NationalitiesList = new List<string>
                {
                    "Akan",
                    "Allemand",
                    "Amharique",
                    "Anglais",
                    "Arabe",
                    "Assamais",
                    "Awadhi",
                    "Azéri",
                    "Bengali",
                    "Bhojpouri",
                    "Birman",
                    "Chewa (nyanja)",
                    "Chhattisgarhi",
                    "Chinois cantonais",
                    "Chinois gan",
                    "Chinois hakka",
                    "Chinois jing",
                    "Chinois mandarin",
                    "Chinois min",
                    "Chinois min bei",
                    "Chinois wu",
                    "Chinois xiang",
                    "Chinois zhouang",
                    "Chittagonien",
                    "Coréen",
                    "Créole haïtien",
                    "Deccan",
                    "Espagnol",
                    "Filipino (tagalog)",
                    "Français",
                    "Grec",
                    "Gujarati",
                    "Haoussa",
                    "Haryanvi",
                    "Hindi /ourdou",
                    "Hongrois",
                    "Igbo (ibo)",
                    "Italien",
                    "Japonais",
                    "Javanais",
                    "Kannada",
                    "Kazakh",
                    "Khmer",
                    "Kurde",
                    "Madourais",
                    "Magahi",
                    "Maithili",
                    "Malais",
                    "Malayalam",
                    "Malgache",
                    "Marathi",
                    "Marwari",
                    "Néerlandais",
                    "Oriya (odiya)",
                    "Oromo",
                    "Ouzbek",
                    "Pachtou",
                    "Panjabi",
                    "Persan",
                    "Peul (fulani)",
                    "Polonais",
                    "Portugais",
                    "Roumain",
                    "Russe",
                    "Saraiki",
                    "Sindhi",
                    "Somali",
                    "Soundanais",
                    "Sylheti",
                    "Tamoul",
                    "Tchèque",
                    "Télougou",
                    "Thaï",
                    "Turc",
                    "Turkmène",
                    "Ukrainien",
                    "Vietnamien",
                    "Visayan (cibuano)",
                    "Yorouba",
                    "Zoulou",


                };
                return NationalitiesList;
            }
            catch (Exception)
            {
                return null;
            }
        }


        public static IEnumerable<string> NationalitiesList()
        {
            try
            {
                List<string> NationalitiesList = new List<string>
                {
                    //DisplayName.SelectNationality,
                    "Afghane",
                    "Albanaise",
                    "Algerienne",
                    "Allemande",
                    "Americaine",
                    "Andorrane",
                    "Angolaise",
                    "Antiguaise et barbudienne",
                    "Argentine",
                    "Armenienne",
                    "Australienne",
                    "Autrichienne",
                    "Azerbaïdjanaise",
                    "Bahamienne",
                    "Bahreinienne",
                    "Bangladaise",
                    "Barbadienne",
                    "Belge",
                    "Belizienne",
                    "Beninoise",
                    "Bhoutanaise",
                    "Bielorusse",
                    "Birmane",
                    "Bissau-Guinéenne",
                    "Bolivienne",
                    "Bosnienne",
                    "Botswanaise",
                    "Bresilienne",
                    "Britannique",
                    "Bruneienne",
                    "Bulgare",
                    "Burkinabe",
                    "Burundaise",
                    "Cambodgienne",
                    "Camerounaise",
                    "Canadienne",
                    "Cap-verdienne",
                    "Centrafricaine",
                    "Chilienne",
                    "Chinoise",
                    "Chypriote",
                    "Colombienne",
                    "Comorienne",
                    "Congolaise",
                    "Costaricaine",
                    "Croate",
                    "Cubaine",
                    "Danoise",
                    "Djiboutienne",
                    "Dominicaine",
                    "Dominiquaise",
                    "Egyptienne",
                    "Emirienne",
                    "Equato-guineenne",
                    "Equatorienne",
                    "Erythreenne",
                    "Espagnole",
                    "Est-timoraise",
                    "Estonienne",
                    "Ethiopienne",
                    "Fidjienne",
                    "Finlandaise",
                    "Française", // enlever de l'ordre alphabétique pour se retrouver à l'index 0
                    "Gabonaise",
                    "Gambienne",
                    "Georgienne",
                    "Ghaneenne",
                    "Grenadienne",
                    "Guatemalteque",
                    "Guineenne",
                    "Guyanienne",
                    "Haïtienne",
                    "Hellenique",
                    "Hondurienne",
                    "Hongroise",
                    "Indienne",
                    "Indonesienne",
                    "Irakienne",
                    "Irlandaise",
                    "Islandaise",
                    "Israélienne",
                    "Italienne",
                    "Ivoirienne",
                    "Jamaïcaine",
                    "Japonaise",
                    "Jordanienne",
                    "Kazakhstanaise",
                    "Kenyane",
                    "Kirghize",
                    "Kiribatienne",
                    "Kittitienne-et-nevicienne",
                    "Kossovienne",
                    "Koweitienne",
                    "Laotienne",
                    "Lesothane",
                    "Lettone",
                    "Libanaise",
                    "Liberienne",
                    "Libyenne",
                    "Liechtensteinoise",
                    "Lituanienne",
                    "Luxembourgeoise",
                    "Macedonienne",
                    "Malaisienne",
                    "Malawienne",
                    "Maldivienne",
                    "Malgache",
                    "Malienne",
                    "Maltaise",
                    "Marocaine",
                    "Marshallaise",
                    "Mauricienne",
                    "Mauritanienne",
                    "Mexicaine",
                    "Micronesienne",
                    "Moldave",
                    "Monegasque",
                    "Mongole",
                    "Montenegrine",
                    "Mozambicaine",
                    "Namibienne",
                    "Nauruane",
                    "Neerlandaise",
                    "Neo-zelandaise",
                    "Nepalaise",
                    "Nicaraguayenne",
                    "Nigeriane",
                    "Nigerienne",
                    "Nord-coréenne",
                    "Norvegienne",
                    "Omanaise",
                    "Ougandaise",
                    "Ouzbeke",
                    "Pakistanaise",
                    "Palau",
                    "Palestinienne",
                    "Panameenne",
                    "Papouane-neoguineenne",
                    "Paraguayenne",
                    "Peruvienne",
                    "Philippine",
                    "Polonaise",
                    "Portoricaine",
                    "Portugaise",
                    "Qatarienne",
                    "Roumaine",
                    "Russe",
                    "Rwandaise",
                    "Saint-lucienne",
                    "Saint-marinaise",
                    "Saint-vincentaise-et-grenadine",
                    "Salomonaise",
                    "Salvadorienne",
                    "Samoane",
                    "Santomeenne",
                    "Saoudienne",
                    "Senegalaise",
                    "Serbe",
                    "Seychelloise",
                    "Sierra-leonaise",
                    "Singapourienne",
                    "Slovaque",
                    "Slovene",
                    "Somalienne",
                    "Soudanaise",
                    "Sri-lankaise",
                    "Sud-africaine",
                    "Sud-coréenne",
                    "Suedoise",
                    "Suisse",
                    "Surinamaise",
                    "Swazie",
                    "Syrienne",
                    "Tadjike",
                    "Taiwanaise",
                    "Tanzanienne",
                    "Tchadienne",
                    "Tcheque",
                    "Thaïlandaise",
                    "Togolaise",
                    "Tonguienne",
                    "Trinidadienne",
                    "Tunisienne",
                    "Turkmene",
                    "Turque",
                    "Tuvaluane",
                    "Ukrainienne",
                    "Uruguayenne",
                    "Vanuatuane",
                    "Venezuelienne",
                    "Vietnamienne",
                    "Yemenite",
                    "Zambienne",
                    "Zimbabweenne"
                };
                return NationalitiesList;
            }
            catch (Exception)
            {
                return null;
            }
        }

        public static IEnumerable<string> PaysList()
        {
            try
            {
                return new List<string>
                {
                    "Afrique du Sud",
                    "Afghanistan",
                    "Albanie",
                    "Algérie",
                    "Allemagne",
                    "Andorre",
                    "Angola",
                    "Antigua-et-Barbuda",
                    "Arabie Saoudite",
                    "Argentine",
                    "Arménie",
                    "Australie",
                    "Autriche",
                    "Azerbaïdjan",
                    "Bahamas",
                    "Bahreïn",
                    "Bangladesh",
                    "Barbade",
                    "Belgique",
                    "Belize",
                    "Bénin",
                    "Bhoutan",
                    "Biélorussie",
                    "Birmanie",
                    "Bolivie",
                    "Bosnie-Herzégovine",
                    "Botswana",
                    "Brésil",
                    "Brunei",
                    "Bulgarie",
                    "Burkina Faso",
                    "Burundi",
                    "Cambodge",
                    "Cameroun",
                    "Canada",
                    "Cap-Vert",
                    "Chili",
                    "Chine",
                    "Chypre",
                    "Colombie",
                    "Comores",
                    "Corée du Nord",
                    "Corée du Sud",
                    "Costa Rica",
                    "Côte d’Ivoire",
                    "Croatie",
                    "Cuba",
                    "Danemark",
                    "Djibouti",
                    "Dominique",
                    "Égypte",
                    "Émirats arabes unis",
                    "Équateur",
                    "Érythrée",
                    "Espagne",
                    "Eswatini",
                    "Estonie",
                    "États-Unis",
                    "Éthiopie",
                    "Fidji",
                    "Finlande",
                    "France",
                    "Gabon",
                    "Gambie",
                    "Géorgie",
                    "Ghana",
                    "Grèce",
                    "Grenade",
                    "Guatemala",
                    "Guinée",
                    "Guinée équatoriale",
                    "Guinée-Bissau",
                    "Guyana",
                    "Haïti",
                    "Honduras",
                    "Hongrie",
                    "Îles Cook",
                    "Îles Marshall",
                    "Inde",
                    "Indonésie",
                    "Irak",
                    "Iran",
                    "Irlande",
                    "Islande",
                    "Israël",
                    "Italie",
                    "Jamaïque",
                    "Japon",
                    "Jordanie",
                    "Kazakhstan",
                    "Kenya",
                    "Kirghizistan",
                    "Kiribati",
                    "Koweït",
                    "Laos",
                    "Lesotho",
                    "Lettonie",
                    "Liban",
                    "Liberia",
                    "Libye",
                    "Liechtenstein",
                    "Lituanie",
                    "Luxembourg",
                    "Macédoine",
                    "Madagascar",
                    "Malaisie",
                    "Malawi",
                    "Maldives",
                    "Mali",
                    "Malte",
                    "Maroc",
                    "Maurice",
                    "Mauritanie",
                    "Mexique",
                    "Micronésie",
                    "Moldavie",
                    "Monaco",
                    "Mongolie",
                    "Monténégro",
                    "Mozambique",
                    "Namibie",
                    "Nauru",
                    "Népal",
                    "Nicaragua",
                    "Niger",
                    "Nigeria",
                    "Niue",
                    "Norvège",
                    "Nouvelle-Zélande",
                    "Oman",
                    "Ouganda",
                    "Ouzbékistan",
                    "Pakistan",
                    "Palaos",
                    "Palestine",
                    "Panama",
                    "Papouasie-Nouvelle-Guinée",
                    "Paraguay",
                    "Pays-Bas",
                    "Pérou",
                    "Philippines",
                    "Pologne",
                    "Portugal",
                    "Qatar",
                    "République centrafricaine",
                    "République démocratique du Congo",
                    "République Dominicaine",
                    "République du Congo",
                    "République tchèque",
                    "Roumanie",
                    "Royaume-Uni",
                    "Russie",
                    "Rwanda",
                    "Saint-Kitts-et-Nevis",
                    "Saint-Vincent-et-les-Grenadines",
                    "Sainte-Lucie",
                    "Saint-Marin",
                    "Salomon",
                    "Salvador",
                    "Samoa",
                    "São Tomé-et-Principe",
                    "Sénégal",
                    "Serbie",
                    "Seychelles",
                    "Sierra Leone",
                    "Singapour",
                    "Slovaquie",
                    "Slovénie",
                    "Somalie",
                    "Soudan",
                    "Soudan du Sud",
                    "Sri Lanka",
                    "Suède",
                    "Suisse",
                    "Suriname",
                    "Syrie",
                    "Tadjikistan",
                    "Tanzanie",
                    "Tchad",
                    "Thaïlande",
                    "Timor oriental",
                    "Togo",
                    "Tonga",
                    "Trinité-et-Tobago",
                    "Tunisie",
                    "Turkménistan",
                    "Turquie",
                    "Tuvalu",
                    "Ukraine",
                    "Uruguay",
                    "Vanuatu",
                    "Vatican",
                    "Venezuela",
                    "Viêt Nam",
                    "Yémen",
                    "Zambie",
                    "Zimbabwe",
                };
            }
            catch (Exception)
            {
                return null;
            }
        }

        public IEnumerable<CountryVM> CountriesList(string ParentPath = "ms-appx:///Assets/Icons/RoundedFlags/svg/")
        {
            try
            {
                return new List<CountryVM>()
            {
                new CountryVM()  { Id = 1, Name = "Afrique du Sud", ImageSource = null},
                new CountryVM()  { Id = 2, Name = "Afghanistan", ImageSource = null},
                new CountryVM()  { Id = 3, Name = "Albanie", ImageSource = null},
                new CountryVM()  { Id = 4, Name = "Algérie", ImageSource = null},
                new CountryVM()  { Id = 5, Name = "Allemagne", ImageSource = null},
                new CountryVM()  { Id = 6, Name = "Andorre", ImageSource = null},
                new CountryVM()  { Id = 7, Name = "Angola", ImageSource = null},
                new CountryVM()  { Id = 8, Name = "Antigua-et-Barbuda", ImageSource = null},
                new CountryVM()  { Id = 9, Name = "Arabie Saoudite", ImageSource = null},
                new CountryVM()  { Id = 10, Name = "Argentine", ImageSource = null},
                new CountryVM()  { Id = 11, Name = "Arménie", ImageSource = null},
                new CountryVM()  { Id = 12, Name = "Australie", ImageSource = null},
                new CountryVM()  { Id = 13, Name = "Autriche", ImageSource = null},
                new CountryVM()  { Id = 14, Name = "Azerbaïdjan", ImageSource = null},
                new CountryVM()  { Id = 15, Name = "Bahamas", ImageSource = null},
                new CountryVM()  { Id = 16, Name = "Bahreïn", ImageSource = null},
                new CountryVM()  { Id = 17, Name = "Bangladesh", ImageSource = null},
                new CountryVM()  { Id = 18, Name = "Barbade", ImageSource = null},
                new CountryVM()  { Id = 19, Name = "Belgique", ImageSource = null},
                new CountryVM()  { Id = 20, Name = "Belize", ImageSource = null},
                new CountryVM()  { Id = 21, Name = "Bénin", ImageSource = null},
                new CountryVM()  { Id = 22, Name = "Bhoutan", ImageSource = null},
                new CountryVM()  { Id = 23, Name = "Biélorussie", ImageSource = null},
                new CountryVM()  { Id = 24, Name = "Birmanie", ImageSource = null},
                new CountryVM()  { Id = 25, Name = "Bolivie", ImageSource = null},
                new CountryVM()  { Id = 26, Name = "Bosnie-Herzégovine", ImageSource = null},
                new CountryVM()  { Id = 27, Name = "Botswana", ImageSource = null},
                new CountryVM()  { Id = 28, Name = "Brésil", ImageSource = null},
                new CountryVM()  { Id = 29, Name = "Brunei", ImageSource = null},
                new CountryVM()  { Id = 30, Name = "Bulgarie", ImageSource = null},
                new CountryVM()  { Id = 31, Name = "Burkina Faso", ImageSource = null},
                new CountryVM()  { Id = 32, Name = "Burundi", ImageSource = null},
                new CountryVM()  { Id = 33, Name = "Cambodge", ImageSource = null},
                new CountryVM()  { Id = 34, Name = "Cameroun", ImageSource = null},
                new CountryVM()  { Id = 35, Name = "Canada", ImageSource = null},
                new CountryVM()  { Id = 36, Name = "Cap-Vert", ImageSource = null},
                new CountryVM()  { Id = 37, Name = "Chili", ImageSource = null},
                new CountryVM()  { Id = 38, Name = "Chine", ImageSource = $"{ParentPath}china.svg"},
                new CountryVM()  { Id = 39, Name = "Chypre", ImageSource = null},
                new CountryVM()  { Id = 40, Name = "Colombie", ImageSource = null},
                new CountryVM()  { Id = 41, Name = "Comores", ImageSource = null},
                new CountryVM()  { Id = 42, Name = "Corée du Nord", ImageSource = null},
                new CountryVM()  { Id = 43, Name = "Corée du Sud", ImageSource = $"{ParentPath}south-korea.svg"},
                new CountryVM()  { Id = 44, Name = "Costa Rica", ImageSource = null},
                new CountryVM()  { Id = 45, Name = "Côte d’Ivoire", ImageSource = null},
                new CountryVM()  { Id = 46, Name = "Croatie", ImageSource = null},
                new CountryVM()  { Id = 47, Name = "Cuba", ImageSource = null},
                new CountryVM()  { Id = 48, Name = "Danemark", ImageSource = null},
                new CountryVM()  { Id = 49, Name = "Djibouti", ImageSource = null},
                new CountryVM()  { Id = 50, Name = "Dominique", ImageSource = null},
                new CountryVM()  { Id = 51, Name = "Égypte", ImageSource = null},
                new CountryVM()  { Id = 52, Name = "Émirats arabes unis", ImageSource = null},
                new CountryVM()  { Id = 53, Name = "Équateur", ImageSource = null},
                new CountryVM()  { Id = 54, Name = "Érythrée", ImageSource = null},
                new CountryVM()  { Id = 55, Name = "Espagne", ImageSource = null},
                new CountryVM()  { Id = 56, Name = "Eswatini", ImageSource = null},
                new CountryVM()  { Id = 57, Name = "Estonie", ImageSource = null},
                new CountryVM()  { Id = 58, Name = "États-Unis", ImageSource = $"{ParentPath}united-states-of-america.svg"},
                new CountryVM()  { Id = 59, Name = "Éthiopie", ImageSource = null},
                new CountryVM()  { Id = 60, Name = "Fidji", ImageSource = null},
                new CountryVM()  { Id = 61, Name = "Finlande", ImageSource = null},
                new CountryVM()  { Id = 62, Name = "France", ImageSource = $"{ParentPath}france.svg"},
                new CountryVM()  { Id = 63, Name = "Gabon", ImageSource = null},
                new CountryVM()  { Id = 64, Name = "Gambie", ImageSource = null},
                new CountryVM()  { Id = 65, Name = "Géorgie", ImageSource = null},
                new CountryVM()  { Id = 66, Name = "Ghana", ImageSource = null},
                new CountryVM()  { Id = 67, Name = "Grèce", ImageSource = null},
                new CountryVM()  { Id = 68, Name = "Grenade", ImageSource = null},
                new CountryVM()  { Id = 69, Name = "Guatemala", ImageSource = null},
                new CountryVM()  { Id = 70, Name = "Guinée", ImageSource = null},
                new CountryVM()  { Id = 71, Name = "Guinée équatoriale", ImageSource = null},
                new CountryVM()  { Id = 72, Name = "Guinée-Bissau", ImageSource = null},
                new CountryVM()  { Id = 73, Name = "Guyana", ImageSource = null},
                new CountryVM()  { Id = 74, Name = "Haïti", ImageSource = null},
                new CountryVM()  { Id = 75, Name = "Honduras", ImageSource = null},
                new CountryVM()  { Id = 76, Name = "Hongrie", ImageSource = null},
                new CountryVM()  { Id = 77, Name = "Îles Cook", ImageSource = null},
                new CountryVM()  { Id = 78, Name = "Îles Marshall", ImageSource = null},
                new CountryVM()  { Id = 79, Name = "Inde", ImageSource = null},
                new CountryVM()  { Id = 80, Name = "Indonésie", ImageSource = null},
                new CountryVM()  { Id = 81, Name = "Irak", ImageSource = null},
                new CountryVM()  { Id = 82, Name = "Iran", ImageSource = null},
                new CountryVM()  { Id = 83, Name = "Irlande", ImageSource = null},
                new CountryVM()  { Id = 84, Name = "Islande", ImageSource = null},
                new CountryVM()  { Id = 85, Name = "Israël", ImageSource = null},
                new CountryVM()  { Id = 86, Name = "Italie", ImageSource = $"{ParentPath}italy.svg"},
                new CountryVM()  { Id = 87, Name = "Jamaïque", ImageSource = null},
                new CountryVM()  { Id = 88, Name = "Japon", ImageSource = $"{ParentPath}japan.svg"},
                new CountryVM()  { Id = 89, Name = "Jordanie", ImageSource = null},
                new CountryVM()  { Id = 90, Name = "Kazakhstan", ImageSource = null},
                new CountryVM()  { Id = 91, Name = "Kenya", ImageSource = null},
                new CountryVM()  { Id = 92, Name = "Kirghizistan", ImageSource = null},
                new CountryVM()  { Id = 93, Name = "Kiribati", ImageSource = null},
                new CountryVM()  { Id = 94, Name = "Koweït", ImageSource = null},
                new CountryVM()  { Id = 95, Name = "Laos", ImageSource = null},
                new CountryVM()  { Id = 96, Name = "Lesotho", ImageSource = null},
                new CountryVM()  { Id = 97, Name = "Lettonie", ImageSource = null},
                new CountryVM()  { Id = 98, Name = "Liban", ImageSource = null},
                new CountryVM()  { Id = 99, Name = "Liberia", ImageSource = null},
                new CountryVM()  { Id = 100, Name = "Libye", ImageSource = null},
                new CountryVM()  { Id = 101, Name = "Liechtenstein", ImageSource = null},
                new CountryVM()  { Id = 102, Name = "Lituanie", ImageSource = null},
                new CountryVM()  { Id = 103, Name = "Luxembourg", ImageSource = null},
                new CountryVM()  { Id = 104, Name = "Macédoine", ImageSource = null},
                new CountryVM()  { Id = 105, Name = "Madagascar", ImageSource = null},
                new CountryVM()  { Id = 106, Name = "Malaisie", ImageSource = null},
                new CountryVM()  { Id = 107, Name = "Malawi", ImageSource = null},
                new CountryVM()  { Id = 108, Name = "Maldives", ImageSource = null},
                new CountryVM()  { Id = 109, Name = "Mali", ImageSource = null},
                new CountryVM()  { Id = 110, Name = "Malte", ImageSource = null},
                new CountryVM()  { Id = 111, Name = "Maroc", ImageSource = null},
                new CountryVM()  { Id = 112, Name = "Maurice", ImageSource = null},
                new CountryVM()  { Id = 113, Name = "Mauritanie", ImageSource = null},
                new CountryVM()  { Id = 114, Name = "Mexique", ImageSource = null},
                new CountryVM()  { Id = 115, Name = "Micronésie", ImageSource = null},
                new CountryVM()  { Id = 116, Name = "Moldavie", ImageSource = null},
                new CountryVM()  { Id = 117, Name = "Monaco", ImageSource = null},
                new CountryVM()  { Id = 118, Name = "Mongolie", ImageSource = null},
                new CountryVM()  { Id = 119, Name = "Monténégro", ImageSource = null},
                new CountryVM()  { Id = 120, Name = "Mozambique", ImageSource = null},
                new CountryVM()  { Id = 121, Name = "Namibie", ImageSource = null},
                new CountryVM()  { Id = 122, Name = "Nauru", ImageSource = null},
                new CountryVM()  { Id = 123, Name = "Népal", ImageSource = null},
                new CountryVM()  { Id = 124, Name = "Nicaragua", ImageSource = null},
                new CountryVM()  { Id = 125, Name = "Niger", ImageSource = null},
                new CountryVM()  { Id = 126, Name = "Nigeria", ImageSource = null},
                new CountryVM()  { Id = 127, Name = "Niue", ImageSource = null},
                new CountryVM()  { Id = 128, Name = "Norvège", ImageSource = null},
                new CountryVM()  { Id = 129, Name = "Nouvelle-Zélande", ImageSource = null},
                new CountryVM()  { Id = 130, Name = "Oman", ImageSource = null},
                new CountryVM()  { Id = 131, Name = "Ouganda", ImageSource = null},
                new CountryVM()  { Id = 132, Name = "Ouzbékistan", ImageSource = null},
                new CountryVM()  { Id = 133, Name = "Pakistan", ImageSource = null},
                new CountryVM()  { Id = 134, Name = "Palaos", ImageSource = null},
                new CountryVM()  { Id = 135, Name = "Palestine", ImageSource = null},
                new CountryVM()  { Id = 136, Name = "Panama", ImageSource = null},
                new CountryVM()  { Id = 137, Name = "Papouasie-Nouvelle-Guinée", ImageSource = null},
                new CountryVM()  { Id = 138, Name = "Paraguay", ImageSource = null},
                new CountryVM()  { Id = 139, Name = "Pays-Bas", ImageSource = null},
                new CountryVM()  { Id = 140, Name = "Pérou", ImageSource = null},
                new CountryVM()  { Id = 141, Name = "Philippines", ImageSource = null},
                new CountryVM()  { Id = 142, Name = "Pologne", ImageSource = null},
                new CountryVM()  { Id = 143, Name = "Portugal", ImageSource = null},
                new CountryVM()  { Id = 144, Name = "Qatar", ImageSource = null},
                new CountryVM()  { Id = 145, Name = "République centrafricaine", ImageSource = null},
                new CountryVM()  { Id = 146, Name = "République démocratique du Congo", ImageSource = null},
                new CountryVM()  { Id = 147, Name = "République Dominicaine", ImageSource = null},
                new CountryVM()  { Id = 148, Name = "République du Congo", ImageSource = null},
                new CountryVM()  { Id = 149, Name = "République tchèque", ImageSource = null},
                new CountryVM()  { Id = 150, Name = "Roumanie", ImageSource = null},
                new CountryVM()  { Id = 151, Name = "Royaume-Uni", ImageSource = null},
                new CountryVM()  { Id = 152, Name = "Russie", ImageSource = null},
                new CountryVM()  { Id = 153, Name = "Rwanda", ImageSource = null},
                new CountryVM()  { Id = 154, Name = "Saint-Kitts-et-Nevis", ImageSource = null},
                new CountryVM()  { Id = 155, Name = "Saint-Vincent-et-les-Grenadines", ImageSource = null},
                new CountryVM()  { Id = 156, Name = "Sainte-Lucie", ImageSource = null},
                new CountryVM()  { Id = 157, Name = "Saint-Marin", ImageSource = null},
                new CountryVM()  { Id = 158, Name = "Salomon", ImageSource = null},
                new CountryVM()  { Id = 159, Name = "Salvador", ImageSource = null},
                new CountryVM()  { Id = 160, Name = "Samoa", ImageSource = null},
                new CountryVM()  { Id = 161, Name = "São Tomé-et-Principe", ImageSource = null},
                new CountryVM()  { Id = 162, Name = "Sénégal", ImageSource = null},
                new CountryVM()  { Id = 163, Name = "Serbie", ImageSource = null},
                new CountryVM()  { Id = 164, Name = "Seychelles", ImageSource = null},
                new CountryVM()  { Id = 165, Name = "Sierra Leone", ImageSource = null},
                new CountryVM()  { Id = 166, Name = "Singapour", ImageSource = null},
                new CountryVM()  { Id = 167, Name = "Slovaquie", ImageSource = null},
                new CountryVM()  { Id = 168, Name = "Slovénie", ImageSource = null},
                new CountryVM()  { Id = 169, Name = "Somalie", ImageSource = null},
                new CountryVM()  { Id = 170, Name = "Soudan", ImageSource = null},
                new CountryVM()  { Id = 171, Name = "Soudan du Sud", ImageSource = null},
                new CountryVM()  { Id = 172, Name = "Sri Lanka", ImageSource = null},
                new CountryVM()  { Id = 173, Name = "Suède", ImageSource = null},
                new CountryVM()  { Id = 174, Name = "Suisse", ImageSource = null},
                new CountryVM()  { Id = 175, Name = "Suriname", ImageSource = null},
                new CountryVM()  { Id = 176, Name = "Syrie", ImageSource = null},
                new CountryVM()  { Id = 177, Name = "Tadjikistan", ImageSource = null},
                new CountryVM()  { Id = 178, Name = "Tanzanie", ImageSource = null},
                new CountryVM()  { Id = 179, Name = "Tchad", ImageSource = null},
                new CountryVM()  { Id = 180, Name = "Thaïlande", ImageSource = null},
                new CountryVM()  { Id = 181, Name = "Timor oriental", ImageSource = null},
                new CountryVM()  { Id = 182, Name = "Togo", ImageSource = null},
                new CountryVM()  { Id = 183, Name = "Tonga", ImageSource = null},
                new CountryVM()  { Id = 184, Name = "Trinité-et-Tobago", ImageSource = null},
                new CountryVM()  { Id = 185, Name = "Tunisie", ImageSource = null},
                new CountryVM()  { Id = 186, Name = "Turkménistan", ImageSource = null},
                new CountryVM()  { Id = 187, Name = "Turquie", ImageSource = null},
                new CountryVM()  { Id = 188, Name = "Tuvalu", ImageSource = null},
                new CountryVM()  { Id = 189, Name = "Ukraine", ImageSource = null},
                new CountryVM()  { Id = 190, Name = "Uruguay", ImageSource = null},
                new CountryVM()  { Id = 191, Name = "Vanuatu", ImageSource = null},
                new CountryVM()  { Id = 192, Name = "Vatican", ImageSource = null},
                new CountryVM()  { Id = 193, Name = "Venezuela", ImageSource = null},
                new CountryVM()  { Id = 194, Name = "Viêt Nam", ImageSource = null},
                new CountryVM()  { Id = 195, Name = "Yémen", ImageSource = null},
                new CountryVM()  { Id = 196, Name = "Zambie", ImageSource = null},
                new CountryVM()  { Id = 197, Name = "Zimbabwe", ImageSource = null},
            };
            }
            catch (Exception)
            {

                throw;
            }
        }

    }

    public class CountryVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageSource { get; set; }
    }
}
